### ISSUE TITLE
Scheduling an update for multiple classes

### ISSUE THREAD

**Issue by jgirl218** [AndrewLester/update-scheduler#5]
I love the update scheduler for Schoology but I found that I can only schedule a post for one class at a time. Is it possible to schedule a post for multiple classes?

**Comment by AndrewLester** [comment]
Hi, thanks so much for your feedback! You're right; it's currently only possible to schedule an Update for a single course/group. 

Making it so an update can be posted to several courses/groups sounds like a great idea, but it may take a bit of time to implement due to the amount of code that will have to be changed.

Keep an eye on this issue as I'll post updates here as progress is made.

**Comment by AndrewLester** [comment]
Fix is now ready. I'll be testing it more this weekend.

**Comment by AndrewLester** [comment]
Fix is tested and confirmed to be working. A deployment will go up this weekend.

**Comment by AndrewLester** [comment]
Fix is deployed

**Comment by jgirl218** [comment]
Thank you so much!
